# Generated by Django 6.0.2 on 2026-03-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del género')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL amigable')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en filtros')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del juego')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL amigable')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio (USD)')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en inventario')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible y disponible para compra')),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox'), ('SWITCH', 'Nintendo Switch')], default='PC', max_length=20, verbose_name='Plataforma')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('descripcion_corta', models.CharField(blank=True, max_length=300, verbose_name='Descripción breve')),
                ('descripcion_larga', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio con descuento')),
                ('edad_minima', models.IntegerField(blank=True, null=True, verbose_name='Edad mínima recomendada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.genero', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
